version: '3'
services:
  app:
    image: shark/ddm19-idd
    build: .
    working_dir: /app
  build:
    image: maven:3-jdk-8-slim
    volumes:
      - .:/app
      - .cache/m2:/root/.m2
    working_dir: /app
    command: bash
  run:
    image: bde2020/spark-submit
    volumes:
      - .:/app
      - .cache/spark-events:/tmp/spark-events
    working_dir: /app
    environment:
      TRACE: '1'
    command: /app/run.sh
    ports:
      - 4040:4040   # Spark UI
      - 5005:5005   # JVM debug
  history:
    build:
      context: .
      dockerfile: Dockerfile.history
    volumes:
      - .cache/spark-events:/tmp/spark-events
    ports:
      - 18080:18080 # Spark History Server
    environment:
      TRACE: '1'