version: '3'
services:
  app:
    image: shark/ddm19-idd
    build: .
    working_dir: /app
  build:
    image: maven:3-jdk-8-slim
    volumes: [.:/app]
    working_dir: /app
    command: bash
  run:
    image: bde2020/spark-submit
    volumes: [.:/app]
    working_dir: /app
    command:
      - /spark/bin/spark-submit
      - --class
      - de.hpi.spark_tutorial.SimpleSpark
      - --master
      - local[8]
      - --deploy-mode
      - client
      - --total-executor-cores
      - "2"
      - --conf
      - spark.driver.extraJavaOptions=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
      - target/SparkTutorial-1.0.jar
    ports:
      - 5005:5005